# alpaca eval is
prompt_template: "prompt.txt"
annotator: "PairwiseAnnotator"
dataset_path: "example.json"
fn_completions: "openai_completions"
model_output_keys: ["output","0731_rlhf_600"]
golden_label_key: "golden_label"
is_shuffle: False
is_randomize_output_order: False
api_param:
  serviceName: "chatgpt_prompts_completions_query_dataview"
  visitBiz: "BU_cto_dialogue"
  visitBizLine: "BU_cto_dialogue_line"
  visitDomain: "BU_cto"
  cacheInterval: 0
  aes_key: "" # aes密钥，需要申请填写，联系@榆天
  aes_iv: "" # aes密钥，需要申请填写，联系@榆天
  retry_times: 3
  queryConditions: 
      url: 'https://zdfmng.alipay.com/commonQuery/queryData'
      model: "gpt-4"
      max_tokens: "1800"
      n: "1"
      temperature: "0"
      api_key: "" # 接口key，需要申请填写，联系@榆天
      messages: ""
completion_parser_kwargs:
    outputs_to_match:
      -1: "api failed"
      0: '(?:^|\n) ?Output \(a\)?'
      1: '(?:^|\n) ?Output \(b\)?'
      2: '(?:^|\n) ?Equal \(c\)?'
fn_completion_parser: "regex_parser"
batch_size: 1