train: 
  seq_length: 400
  epochs: 1000
  total_steps: 100000
  batch_size: 4
  checkpoint_interval: 1000
  eval_interval: 200
  pipeline: GlmPipeline
  trainer: AcceleratePPOMixTrainer
  tracker: tensorboard
  logging_dir: /mnt/xiaohao.wzh/rlhf/log/log_10bsft_2bmix_freeze_ent_norm
  checkpoint_dir: /mnt/xiaohao.wzh/rlhf/model/ckpt_10bsft_2bmix_freeze_ent_norm
  max_norm: 1.0
model:
  model_path: /ossfs/workspace/data/sft/20230325-203551/checkpoint-15000
  model_arch_type: glm
  num_layers_unfrozen: 2
tokenizer:
  tokenizer_path: /ossfs/workspace/data/sft/20230325-203551/checkpoint-15000
  truncation_side: left
  padding_side: right
optimizer:
  name: adamw
  kwargs:
    lr: 5.0e-6
    betas: 
      - 0.9
      - 0.95
    eps: 1.0e-8
    weight_decay: 0.01
scheduler:
  name: cosine_annealing
  kwargs:
    T_max: 100000
    eta_min: 1.0e-6
method:
  name: PPOMixConfig
  num_rollouts: 128
  chunk_size: 4
  ppo_epochs: 2
  init_kl_coef: 0.1
  # target: 6
  target: null
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: running
  ref_mean: null
  ref_std: null
  cliprange_reward: 50
  ent_coef: 0.0
  gen_kwargs:
    max_new_tokens: 200
    top_k: 0
    top_p: 1.0
    do_sample: false