train: 
  seq_length: 1024
  epochs: 30
  total_steps: 100000
  batch_size: 4
  checkpoint_interval: 1000
  eval_interval: 500
  pipeline: GlmPipeline
  trainer: AcceleratePPOMixTrainer
  tracker: tensorboard
  logging_dir: ./log
  max_norm: 1.0
  gradient_accumulation_steps: 2
model:
  model_path: /ossfs/workspace/pretrained_models/glm-2b-ant
  model_arch_type: glm
  num_layers_unfrozen: 2
tokenizer:
  tokenizer_path: /ossfs/workspace/pretrained_models/glm-2b-ant
  truncation_side: left
  padding_side: right
optimizer:
  name: adamw
  kwargs:
    lr: 1.0e-6
    betas: 
      - 0.9
      - 0.999
    eps: 1.0e-5
    weight_decay: 0.01
scheduler:
  name: cosine_warmup
  kwargs:
    num_warmup_steps: 1000
    num_training_steps: 100000
method:
  name: PPOConfig
  num_rollouts: 4
  chunk_size: 2
  ppo_epochs: 20
  init_kl_coef: 0.1
  target: null
  horizon: 10000
  gamma: 1
  lam: 0.98
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.0001
  scale_reward: ref
  ref_mean: null
  ref_std: null
  cliprange_reward: 2
  gen_kwargs:
    max_new_tokens: 512