train: 
  seq_length: 1024
  epochs: 4000
  total_steps: 100000
  batch_size: 2
  checkpoint_interval: 1000
  eval_interval: 200
  pipeline: GlmPipeline
  trainer: AcceleratePPOMixTrainer
  tracker: tensorboard
  logging_dir: /mnt/xiaohao.wzh/rlhf/log/log_5bsft_10bmix_freeze_cliprange
  checkpoint_dir: /mnt/xiaohao.wzh/rlhf/model/ckpt_5bsft_10bmix_freeze_cliprange
  max_norm: 1.0
  gradient_accumulation_steps: 4
model:
  model_path: /mnt/tangjian.dtj/pretrained_models/glm-5b-sft-v8minus-checkpoint-5528
  model_arch_type: glm
  num_layers_unfrozen: 4
tokenizer:
  tokenizer_path: /mnt/tangjian.dtj/pretrained_models/glm-5b-sft-v8minus-checkpoint-5528
  truncation_side: left
  padding_side: right
optimizer:
  name: adamw
  kwargs:
    lr: 1.0e-6
    betas: 
      - 0.9
      - 0.95
    eps: 1.0e-8
    weight_decay: 0.01
scheduler:
  name: cosine_warmup
  kwargs:
    num_warmup_steps: 1000
    num_training_steps: 100000
method:
  name: PPOConfig
  num_rollouts: 64
  chunk_size: 4
  ppo_epochs: 2
  init_kl_coef: 0.2
  # target: 6
  target: null
  horizon: 10000
  gamma: 0.99
  lam: 0.95
  cliprange: 0.05
  cliprange_value: 0.2
  vf_coef: 1.0
  scale_reward: running
  ref_mean: null
  ref_std: null
  cliprange_reward: 50
  # ent_coef: 0.0
  # kl_early_stop: 30.0
  gen_kwargs:
    max_new_tokens: 512
    top_k: 0
    top_p: 1.0
    do_sample: false
  gen_experience_kwargs:
    max_new_tokens: 512
    do_sample: true
    temperature: 1.0
    top_k: 50
    top_p: 0.95