#FROM reg.docker.alibaba-inc.com/occlum/occlum:0.27.10-hypermode-1.3.0-ubuntu20.04
FROM occlum/hyperenclave:0.27.10-hypermode-1.3.0-ubuntu20.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    flex \
    libgeos-dev \
    libgdal-dev \
    liblz4-dev \
    python3-dev \
    libnuma-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add postgres demo 
ADD ./postgres /root/demos/postgres/

# Build Occlum PG demo
## 1. Install python packages
## 2. Build and install PG
## 3. Build PG demo
ARG SGX_MODE=HYPER
ENV PATH=/usr/local/pgsql/bin:$PATH
WORKDIR /root/demos/postgres
RUN ./install_python_with_conda.sh && \
    ./build_pg.sh && \
    SGX_MODE=$SGX_MODE ./build_occlum_instance.sh && \
    rm -rf occlum_instance/image

CMD ["bash"]
