compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: antllm/examples/rlhf/rl/configs/ds_config_trlx_bf16.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_port: '22222'
main_training_function: main
num_machines: 1
num_processes: 7
rdzv_backend: static
same_network: true
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
