# alpaca eval is
prompt_template: "prompt_identity.txt"
annotator: "MultiturnSingleAnnotator"
dataset_path: "多轮身份测试_multiturn.json"
fn_completions: "openai_completions"
model_output_keys: ["input"]
golden_label_key: "golden_label"
is_shuffle: False
is_randomize_output_order: False
api_param:
  serviceName: "chatgpt_prompts_completions_query_dataview"
  visitBiz: "BU_cto_dialogue"
  visitBizLine: "BU_cto_dialogue_line"
  visitDomain: "BU_cto"
  cacheInterval: 0
  aes_key: "" # aes密钥，需要申请填写，联系@榆天
  aes_iv: "" # aes密钥，需要申请填写，联系@榆天
  retry_times: 10
  queryConditions: 
      # url: 'https://zdfmng-pre.alipay.com/commonQuery/queryData'
      url: 'https://zdfmng.alipay.com/commonQuery/queryData'
      model: "gpt-3.5-turbo"
      max_tokens: "3000"
      n: "1"
      temperature: "0"
      api_key: "" # 接口key，需要申请填写，联系@榆天
      messages: ""
completion_parser_kwargs:
    outputs_to_match:
      -1: "api failed"
      1: '(?:^|\n) ?正确 \(a\)?'
      0: '(?:^|\n) ?错误 \(b\)?'
fn_completion_parser: "regex_parser"
batch_size: 1